// <auto-generated />
using System;
using Investment_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investment_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Investment_Tracker.Entities.Asset", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Investment_Tracker.Entities.Investment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("assetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("buyDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("buyPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("assetId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("Investment_Tracker.Entities.Investment", b =>
                {
                    b.HasOne("Investment_Tracker.Entities.Asset", "asset")
                        .WithMany()
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");
                });
#pragma warning restore 612, 618
        }
    }
}
